### ISSUE TITLE
This is not clear

### ISSUE THREAD

**Issue by kamlesh131986** [Microsoft/TypeScript-WeChat-Starter#1]
It's content in china language, these points are not clear, please help guide change to english version

**Comment by coolboygym** [comment]
矫枉过正了吧

**Comment by wilsunson** [comment]
so all you need is to learn more about our language,english version is not necessary for ours wechat developers.

**Comment by ghost** [comment]
The English documentation is the file called `README_en.md`. Let's close this issue.

**Comment by wilsunson** [comment]
just do it

**Comment by ghost** [comment]
Awh, you should've replied in 2020, and have the issue closed in 2021.

**Comment by julien-c** [comment]
Ooh the snark is strong here :)
